Настроила React-Router
htmlacademy-react/662355-what-to-watch-12 pull request #4
Opened 2023-03-09 14:50 UTC by EvaD23

2023-03-10 11:49 UTC, Oleg979 requested changes

2023-03-10 11:49 UTC, Oleg979 commented on project/src/components/private-route.tsx
> +type PrivateRouteProps = {
В этом случае реакт предоставляет нам встроенный тип PropsWithChildren. Удобнее и правильнее было бы использовать его

2023-03-10 11:49 UTC, Oleg979 commented on project/src/components/private-route.tsx
> +  const hasAccess = false;
По задумке мы хотим получать эту штуку снаружи в виде пропса. В принципе, переделать можно будет и в следующей домашке, но думаю в условии имелось в виду уже сейчас передавать false снаружи

2023-03-11 15:18 UTC, EvaD23 commented on project/src/components/private-route.tsx
> +type PrivateRouteProps = {
У меня не получается добавить PropsWithChildren, так как нужно вернуть JSX.element.  Тип children в  PropsWithChildren является null | undefined | string и тд.

2023-03-11 15:19 UTC, EvaD23 commented on project/src/components/private-route.tsx
> +  const hasAccess = false;
Вынесла hasAccess  в props

2023-03-13 08:13 UTC, merged