Больше подробностей (часть 2)
htmlacademy-react/662355-what-to-watch-12 pull request #7
Opened 2023-03-27 12:09 UTC by EvaD23

---
:mortar_board: [Больше подробностей (часть 2)](https://up.htmlacademy.ru/react/12/user/662355/tasks/9)

2023-03-27 23:54 UTC, Oleg979 requested changes

2023-03-27 23:54 UTC, Oleg979 commented on project/src/pages/film-layout/film.tsx
> +        {
Я бы вынес это в отдельный компонент, но не забивал эту логику прям сюда. Лучше сделать компонент <SameFilms film={film}>

2023-03-27 23:54 UTC, Oleg979 commented on project/src/components/reviews/reviews.tsx
> +    <Tabs id={parseInt(id, 10)} choosedTabs={choosedTab}>
Компонент таб выглядит как часть layoutа страницы. Вместо того, чтобы рендерить его каждый раз заново и вдобавок вручную передавать активную табу, можно рендерить табы один раз(в роутах либо в родительском компоненте всех таб), а активную табу получать из параметров урл

2023-03-29 13:44 UTC, EvaD23 commented on project/src/pages/film-layout/film.tsx
> +        {
вынесла

2023-03-29 13:45 UTC, EvaD23 commented on project/src/components/reviews/reviews.tsx
> +    <Tabs id={parseInt(id, 10)} choosedTabs={choosedTab}>
перенесла

2023-03-31 11:39 UTC, merged