Добавила фильтр по жанрам
htmlacademy-react/662355-what-to-watch-12 pull request #8
Opened 2023-03-31 11:44 UTC by EvaD23

2023-04-03 11:14 UTC, Oleg979 requested changes

2023-04-03 11:14 UTC, Oleg979 commented on project/src/components/genre-list/genre-list.tsx
> +  }, [currGenre, dispatch, films]);
Вряд ли у тебя когда-то поменяется dispatch

2023-04-03 11:14 UTC, Oleg979 commented on project/src/pages/main/main.tsx
> +  const [filmsByGenre, setFilmsByGender] = useState(films);
Genre*

2023-04-04 11:10 UTC, EvaD23 commented on project/src/pages/main/main.tsx
> +  const [filmsByGenre, setFilmsByGender] = useState(films);
поправила

2023-04-04 11:11 UTC, EvaD23 commented on project/src/components/genre-list/genre-list.tsx
> +  }, [currGenre, dispatch, films]);
Ага, я тут что-то совсем не то наворотила. Только когда попробовала 7.1 делать поняла, как нужно было сделать и переделала

2023-04-05 08:12 UTC, merged